title: Dayda
name: Department of the Interior
description: >-
  This is a catalog of datasets organized and made more accessible from the
  Department of Interior, providing simple dowloadable CSV and JSON files, as
  well as Postman Collections you can use as part of workflows and other
  automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: >-
  https://www.doi.gov/sites/doi.opengov.ibmcloud.com/themes/custom/doi_gov/logo.png
favicon: /assets/img/favicon.png
url: 'http://department-of-the-interior.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
